### ISSUE TITLE
it can not work in windows, reported "fio: D is not a directory"

### ISSUE THREAD

**Issue by eric-gitta-moore** [OliverLew/fio-cdm#1]
```
Run fio -v
  fio -v
  python[3](https://github.com/james-curtis/fio-cdm/actions/runs/3625681230/jobs/6113979589#step:4:3) fio-cdm -s 1m
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
fio-3.13
fio: D is not a directory
fio: failed parsing directory=D:\a\fio-cdm\fio-cdm
fio: job global dropped
tests: 5, size: 1.0MiB, target: D:\a\fio-cdm\fio-cdm 1.8GiB/1[4](https://github.com/james-curtis/fio-cdm/actions/runs/3625681230/jobs/6113979589#step:4:4).0GiB
```
![image](https://user-images.githubusercontent.com/49338067/205788978-8e5ea077-dd1b-4b15-8c4e-484a58429067.png)

**Comment by xlucn** [comment]
Thanks for the report. I once fixed this before, but I somehow accidentally reverted it later.

I am pushing a new commit to add it back.

Update: having some internet issues, will push later :(

In case you want to try your self, the `directory` parameter needs all colons escaped, like this:

https://github.com/oliverlew/fio-cdm/commit/bd637caf1baced5fc6592f6edf192e88ef590541#diff-dfc272e6e85e6c17d3b129a151ac0326555be146c1cf7b7dca00f9faa10d9562L45

**Comment by xlucn** [comment]
I assume the commit solved the issue, so closing this now. Please comment or reopen if anything comes up.
